print('Sono il file 1')
print('aggiungo una riga')
print('aggiungo una riga bla bla')
print('altro print')
print('Faccio una modifica al file')
print('Sono il file 1')
print('aggiungo una riga')
print('aggiungo una riga bla bla')
print('altro print')
print('Faccio una modifica al file')print('Sono il file 1')
print('aggiungo una riga')
print('aggiungo una riga bla bla')
print('altro print')
print('Faccio una modifica al file')print('Sono il file 1')
print('aggiungo una riga')
print('aggiungo una riga bla bla')
print('altro print')
print('Faccio una modifica al file')print('Sono il file 1')
print('aggiungo una riga')
print('aggiungo una riga bla bla')
print('altro print')
print('Faccio una modifica al file')
